version: '3.8'

networks:
  chaoqer:
    external: true

services:
  chaoqer-$CI_PROJECT_NAME:
    image: $CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME-latest
    networks:
      - chaoqer
    restart: always
    ports:
      - "18080:18080"